version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt

  pre_build:
    commands:
      - python3 --version

artifacts:
  files:
    - '**/*'
